### ISSUE TITLE
Where to place my dataset (split)?

### ISSUE THREAD

**Issue by thiagoribeiro1** [wandb/examples#74] opened 2021-04-15 13:09 UTC
Hello! This repository helped me enormously in realizing that there is potential to use sweeps with k-Fold cross-validation (grouping each split with the same hyperparameters). However, I am very confused on how to adapt my code for this. For example, in the repository code there is no reference to where to place my dataset that will be divided into the folds. Thank you very much!

# WandB – Install the W&B library
%pip install wandb -q
import wandb
from wandb.keras import WandbCallback

!pip install wandb -qq
import numpy as np
import pandas as pd
import wandb
from wandb.keras import WandbCallback
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from keras.models import Sequential
from keras.layers import Dense

dataset = pd.read_excel("Dados gerados Bateria r2.xlsx", "Trial 2", index_col=None, na_values=["NA"], engine="openpyxl")
dataset = dataset.iloc[:,0:11]
dataset['STATUS_bin'] = dataset['STATUS'].apply(lambda x: 1 if x == "OK" else 0)
X = dataset.iloc[:,1:10].values
y = dataset.iloc[:,11].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Configure the sweep – specify the parameters to search through, the search strategy, the optimization metric et all.
sweep_config = {
    'method': 'bayes',
    'metric': {
      'name': 'val_accuracy',
      'goal': 'maximize'   
    },
    'parameters': {
        'epoch': {
            'distribution': 'int_uniform',
            'max': 250,
            'min': 1
        },
        'activation_1': {
            'distribution': 'categorical',
            'values':['linear', 'relu', 'sigmoid']
        },
        'activation_2': {
            'distribution': 'categorical',
            'values':['linear', 'relu', 'sigmoid']
        },
        'activation_3': {
            'distribution': 'categorical',
            'values':['linear', 'relu', 'sigmoid']
        },
        'activation_4': {
            'distribution': 'categorical',
            'values':['linear', 'relu', 'sigmoid']
        },
        'activation_5': {
            'distribution': 'categorical',
            'values':['linear', 'relu', 'sigmoid']
        },
        'n_layers': {
            'distribution': 'int_uniform',
            'max': 5,
            'min': 1
        },
        'layer_1': {
            'distribution': 'int_uniform',
            'max': 100,
            'min': 1
        },
        'layer_2': {
            'distribution': 'int_uniform',
            'max': 100,
            'min': 1
        },
        'layer_3': {
            'distribution': 'int_uniform',
            'max': 100,
            'min': 1
        },
        'layer_4': {
            'distribution': 'int_uniform',
            'max': 100,
            'min': 1
        },
        'layer_5': {
            'distribution': 'int_uniform',
            'max': 100,
            'min': 1
        },
        'optimizer': {
            'distribution': 'categorical',
            'values': ['adam', 'SGD', 'Adadelta']
        },

    }
}

# Initialize a new sweep
sweep_id = wandb.sweep(sweep_config, entity="thiagoribeiro1", project="sweeps-VentilAQUA_4_Bateria2")

def train():
  config_defaults = {
        "n_layers": 1,
        "layer_1": 1,
        "activation_1": "linear",
        #"dropout": 0.3,
        "layer_2": 1,
        "activation_2": "linear",
        "layer_3": 1,
        "activation_3": "linear",
        "layer_4": 1,
        "activation_4": "linear",
        "layer_5": 1,
        "activation_5": "linear",
        "optimizer": "adam",
        #"loss": "binary_crossentropy",
        #"metric": "accuracy",
        "epoch": 100
        #"batch_size": 32
        
    }

  # Initialize a new wandb run
  wandb.init(config=config_defaults)

  # Config is a variable that holds and saves hyperparameters and inputs
  config = wandb.config
  

  model = Sequential()

  if config.n_layers==1:
    model.add(Dense(units=config.layer_1, activation=config.activation_1))    
  if config.n_layers==2:
    model.add(Dense(units=config.layer_1, activation=config.activation_1))
    model.add(Dense(units=config.layer_2, activation=config.activation_2))
  if config.n_layers==3:
    model.add(Dense(units=config.layer_1, activation=config.activation_1))
    model.add(Dense(units=config.layer_2, activation=config.activation_2))
    model.add(Dense(units=config.layer_3, activation=config.activation_3))
  if config.n_layers==4:
    model.add(Dense(units=config.layer_1, activation=config.activation_1))
    model.add(Dense(units=config.layer_2, activation=config.activation_2))
    model.add(Dense(units=config.layer_3, activation=config.activation_3))
    model.add(Dense(units=config.layer_4, activation=config.activation_4))
  if config.n_layers==5:
    model.add(Dense(units=config.layer_1, activation=config.activation_1))
    model.add(Dense(units=config.layer_2, activation=config.activation_2))
    model.add(Dense(units=config.layer_3, activation=config.activation_3))
    model.add(Dense(units=config.layer_4, activation=config.activation_4))
    model.add(Dense(units=config.layer_5, activation=config.activation_5))

  model.add(Dense(1, activation="sigmoid"))

  model.compile(loss='binary_crossentropy', optimizer=config.optimizer, metrics=['accuracy', 'AUC'])

  model.fit(X_train, y_train, batch_size=64, epochs=config.epoch, validation_data=(X_test,y_test), callbacks=[WandbCallback()])

# Initialize a new sweep
wandb.agent(sweep_id, train)

**Comment by vanpelt** [comment] 2021-04-15 17:14
Hey @thiagoribeiro1 I don't understand the question.  Can you try rephrasing it or making it more specific?

**Comment by thiagoribeiro1** [comment] 2021-04-15 17:25
Hello, @vanpelt !!! First of all, thank you very much for your attention. I will try to explain it better. My goal is to perform a sweep on the hyperparameters of a neural network with cross-validation k-Fold. Without k-Fold cross-validation, I have been successful (see the code above). However, I cannot perform this process with k-Fold, that is, grouping the results by folds. I'm trying to get inspired by this code (https://github.com/wandb/examples/blob/master/examples/wandb-sweeps/sweeps-cross-validation/train-cross-validation.py), however I'm lost where to load my dataset (training and testing). Maybe if the code was a practical example with a neural network and a dataset, I would see what to do ...

**Comment by thiagoribeiro1** [comment] 2021-04-15 17:32
@vanpelt, complementing my answer... I have used (without sweeps to optimize hyperparameters) the cross-validation k-Fold, in my codes there is always: skfold = StratifiedKFold (n_splits = 5, shuffle = True, random_state = 7). Followed by a loop: for train, test in skfold.split (X, y) :. Where should I add these lines?

**Comment by vanpelt** [comment] 2021-04-15 17:46
I'm still not sure I understand the question.  All `wandb.agent` does is call the `train` function.  Within this function you'll need to call wandb.init.  After calling wandb.init you can access the current runs hyperparameters by accessing `wandb.run.config`.  Within this training function you can load your dataset, train your model, then evaluate it.  Does that make sense?

**Comment by thiagoribeiro1** [comment] 2021-04-15 17:53
I got access to my code I will share ... This is the code that works perfectly on my machine, but without sweeps (the hyperparameters were defined by me):

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from keras.models import Sequential
from keras.layers import Dense
from keras.callbacks import EarlyStopping
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, ConfusionMatrixDisplay, plot_confusion_matrix, confusion_matrix, precision_score, recall_score
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score



dataset = pd.read_excel(r"C:\Users\thiag\Desktop\Dados gerados Bateria 2\Dados gerados Bateria r2.xlsx", "Trial 2", index_col=None, na_values=["NA"], engine="openpyxl")
dataset = dataset.iloc[:,0:11]
dataset['STATUS_bin'] = dataset['STATUS'].apply(lambda x: 1 if x == "OK" else 0)
X = dataset.iloc[:,1:10].values
y = dataset.iloc[:,11].values

# Define the K-fold Cross Validator
kf = KFold(n_splits=5, random_state=1, shuffle=True)

# Define per-fold score containers
val_accuracy_per_fold = []
val_loss_per_fold = []
val_auc_per_fold = []

# K-fold Cross Validation model evaluation
fold_no = 1
for train, test in kf.split(X, y):
    sc = StandardScaler()
    X[train] = sc.fit_transform(X[train])
    X[test] = sc.transform(X[test])
    
    model = Sequential()
    model.add(Dense(16, input_dim=9, activation="relu"))
    model.add(Dense(12, activation="relu"))
    model.add(Dense(10, activation="relu"))
    model.add(Dense(1, activation="sigmoid"))
    
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy','AUC'])
    
    history = model.fit(
        X[train],
        y[train],
        validation_data=(X[test], y[test]),
        epochs=250,
        batch_size=64,
        )
    val_accuracy_per_fold.append(history.history['val_accuracy'][-1])
    val_loss_per_fold.append(history.history['val_loss'][-1])
    val_auc_per_fold.append(history.history['val_auc'][-1])
    
    fold_no = fold_no + 1

**Comment by thiagoribeiro1** [comment] 2021-04-15 17:56
This is the code that does NOT work with sweeps (optimization of hyperparameters):

import wandb
import os
import multiprocessing
import collections
import random
import numpy as np
import pandas as pd
from wandb.keras import WandbCallback
from sklearn.preprocessing import StandardScaler
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import KFold


Worker = collections.namedtuple("Worker", ("queue", "process"))
WorkerInitData = collections.namedtuple(
    "WorkerInitData", ("num", "sweep_id", "sweep_run_name", "config")
)
WorkerDoneData = collections.namedtuple("WorkerDoneData", ("val_accuracy"))

dataset = pd.read_excel(r"C:\Users\thiag\Desktop\Dados gerados Bateria 2\Dados gerados Bateria r2.xlsx", "Trial 2", index_col=None, na_values=["NA"], engine="openpyxl")
dataset = dataset.iloc[:,0:11]
dataset['STATUS_bin'] = dataset['STATUS'].apply(lambda x: 1 if x == "OK" else 0)
X = dataset.iloc[:,1:10].values
y = dataset.iloc[:,11].values

kf = KFold(n_splits=5, random_state=1, shuffle=True)

def reset_wandb_env():
    exclude = {
        "WANDB_PROJECT",
        "WANDB_ENTITY",
        "WANDB_API_KEY",
    }
    for k, v in os.environ.items():
        if k.startswith("WANDB_") and k not in exclude:
            del os.environ[k]


def train(sweep_q, worker_q):
    reset_wandb_env()
    worker_data = worker_q.get()
    run_name = "{}-{}".format(worker_data.sweep_run_name, worker_data.num)
    config = worker_data.config
    run = wandb.init(
        group=worker_data.sweep_id,
        job_type=worker_data.sweep_run_name,
        name=run_name,
        config=config,
    )
    
    fold_no = 1
    for train, test in kf.split(X, y):
        sc = StandardScaler()
        X[train] = sc.fit_transform(X[train])
        X[test] = sc.transform(X[test])
        model = Sequential()

        if config.n_layers==1:
            model.add(Dense(units=config.layer_1, activation=config.activation_1))    
        if config.n_layers==2:
            model.add(Dense(units=config.layer_1, activation=config.activation_1))
            model.add(Dense(units=config.layer_2, activation=config.activation_2))
        if config.n_layers==3:
            model.add(Dense(units=config.layer_1, activation=config.activation_1))
            model.add(Dense(units=config.layer_2, activation=config.activation_2))
            model.add(Dense(units=config.layer_3, activation=config.activation_3))
        if config.n_layers==4:
            model.add(Dense(units=config.layer_1, activation=config.activation_1))
            model.add(Dense(units=config.layer_2, activation=config.activation_2))
            model.add(Dense(units=config.layer_3, activation=config.activation_3))
            model.add(Dense(units=config.layer_4, activation=config.activation_4))
        if config.n_layers==5:
            model.add(Dense(units=config.layer_1, activation=config.activation_1))
            model.add(Dense(units=config.layer_2, activation=config.activation_2))
            model.add(Dense(units=config.layer_3, activation=config.activation_3))
            model.add(Dense(units=config.layer_4, activation=config.activation_4))
            model.add(Dense(units=config.layer_5, activation=config.activation_5))
    
        model.add(Dense(1, activation="sigmoid"))
        
        model.compile(loss='binary_crossentropy', optimizer=config.optimizer, metrics=['accuracy', 'AUC'])
        history = model.fit(X[train], y[train], batch_size=64, epochs=config.epoch, validation_data=(X[test],y[test]))

    
        
        run.log(dict(val_accuracy=history.history['val_accuracy']))
        wandb.join()
        sweep_q.put(WorkerDoneData(val_accuracy=history.history['val_accuracy']))
        fold_no = fold_no + 1


def main():
    num_folds = 5

    sweep_q = multiprocessing.Queue()
    workers = []
    for num in range(num_folds):
        q = multiprocessing.Queue()
        p = multiprocessing.Process(
            target=train, kwargs=dict(sweep_q=sweep_q, worker_q=q)
        )
        p.start()
        workers.append(Worker(queue=q, process=p))

    sweep_run = wandb.init()
    sweep_id = sweep_run.sweep_id or "unknown"
    sweep_url = sweep_run.get_sweep_url()
    project_url = sweep_run.get_project_url()
    sweep_group_url = "{}/groups/{}".format(project_url, sweep_id)
    sweep_run.notes = sweep_group_url
    sweep_run.save()
    sweep_run_name = sweep_run.name or sweep_run.id or "unknown"

    metrics = []
    for num in range(num_folds):
        worker = workers[num]
        
        worker.queue.put(
            WorkerInitData(
                sweep_id=sweep_id,
                num=num,
                sweep_run_name=sweep_run_name,
                config=dict(sweep_run.config),
            )
        )
        
        result = sweep_q.get()
        
        worker.process.join()
        
        metrics.append(result.val_accuracy)

    sweep_run.log(dict(val_accuracy=sum(metrics) / len(metrics)))
    wandb.join()

    print("*" * 40)
    print("Sweep URL:       ", sweep_url)
    print("Sweep Group URL: ", sweep_group_url)
    print("*" * 40)


if __name__ == "__main__":
    main()

**Comment by thiagoribeiro1** [comment] 2021-04-15 18:01
> 
> 
> I'm still not sure I understand the question. All `wandb.agent` does is call the `train` function. Within this function you'll need to call wandb.init. After calling wandb.init you can access the current runs hyperparameters by accessing `wandb.run.config`. Within this training function you can load your dataset, train your model, then evaluate it. Does that make sense?

@vanpelt, In this code (https://github.com/wandb/examples/blob/master/examples/wandb-sweeps/sweeps-cross-validation/train-cross-validation.py), where I add these lines:

fold_no = 1
for train, test in kf.split(X, y):
    sc = StandardScaler()
    X[train] = sc.fit_transform(X[train])
    X[test] = sc.transform(X[test])
    model = Sequential()

    if config.n_layers==1:
        model.add(Dense(units=config.layer_1, activation=config.activation_1))    
    if config.n_layers==2:
        model.add(Dense(units=config.layer_1, activation=config.activation_1))
        model.add(Dense(units=config.layer_2, activation=config.activation_2))
    if config.n_layers==3:
        model.add(Dense(units=config.layer_1, activation=config.activation_1))
        model.add(Dense(units=config.layer_2, activation=config.activation_2))
        model.add(Dense(units=config.layer_3, activation=config.activation_3))
    if config.n_layers==4:
        model.add(Dense(units=config.layer_1, activation=config.activation_1))
        model.add(Dense(units=config.layer_2, activation=config.activation_2))
        model.add(Dense(units=config.layer_3, activation=config.activation_3))
        model.add(Dense(units=config.layer_4, activation=config.activation_4))
    if config.n_layers==5:
        model.add(Dense(units=config.layer_1, activation=config.activation_1))
        model.add(Dense(units=config.layer_2, activation=config.activation_2))
        model.add(Dense(units=config.layer_3, activation=config.activation_3))
        model.add(Dense(units=config.layer_4, activation=config.activation_4))
        model.add(Dense(units=config.layer_5, activation=config.activation_5))

    model.add(Dense(1, activation="sigmoid"))
    
    model.compile(loss='binary_crossentropy', optimizer=config.optimizer, metrics=['accuracy', 'AUC'])
    history = model.fit(X[train], y[train], batch_size=64, epochs=config.epoch, validation_data=(X[test],y[test]))

**Comment by vanpelt** [comment] 2021-04-15 20:27
Put them here: https://github.com/wandb/examples/blob/master/examples/wandb-sweeps/sweeps-cross-validation/train-cross-validation.py#L39

**Comment by thiagoribeiro1** [comment] 2021-04-15 21:10
@vanpelt, there will be two loops:

1)for num in range(num_folds):
        q = multiprocessing.Queue()
        p = multiprocessing.Process(
            target=train, kwargs=dict(sweep_q=sweep_q, worker_q=q)
        )
        p.start()
        workers.append(Worker(queue=q, process=p))

2)for train, test in kf.split(X, y):

I am confused... :(

**Comment by vanpelt** [comment] 2021-04-15 23:42
Hey @thiagoribeiro1 you could likely simplify the logic by not using multiprocessing and a queue for the k-folds, but if you keep it.  The general flow should be:

```
def train(...):
    wandb.init(...)
    # Train model
    # Do cross validation
    wandb.finish()
wandb.agent("XXX", function=train)
```

**Comment by thiagoribeiro1** [comment] 2021-05-02 14:28
Hey @vanpelt !!! After some time trying in every way, I will ask for help again, please! I adapted the model made available by the wandb, I did some readings of other examples. Evolved in my code (https://github.com/thiagoribeiro1/wandb/blob/main/train-cross-validation_VentilAQUA.py). However, I have not yet been successful. In the end he has an error in running the training of neural networks. In the code, before training the neural network, I split the training / test data with the k-fold. Help me please!!!

**Comment by vanpelt** [comment] 2021-05-03 17:54
@thiagoribeiro1 can you share a colab or the specific errors you're seeing.  We won't be able to help you if we can't reproduce the exact error you're seeing.

**Comment by thiagoribeiro1** [comment] 2021-05-03 19:07
Sorry, @vanpelt! Actually, my screen stays forever like this: 
![image](https://user-images.githubusercontent.com/73705144/116920963-af52ae00-ac29-11eb-8b5a-07f73a90d95c.png)

**Comment by vanpelt** [comment] 2021-05-03 19:19
Can you try running the actual command outside of the agent and see if there's an error message / verify if the command itself hangs?  i.e. `python C:\... --activation_1=relu ...`

**Comment by thiagoribeiro1** [comment] 2021-05-03 19:26
@vanpelt, please, what do you mean for outside the agent?

**Comment by thiagoribeiro1** [comment] 2021-05-03 19:38
> 
> 
> Can you try running the actual command outside of the agent and see if there's an error message / verify if the command itself hangs? i.e. `python C:\... --activation_1=relu ...`

I will, @vanpelt. I understood.

**Comment by thiagoribeiro1** [comment] 2021-05-03 19:56
This is what I got, @vanpelt: 
![image](https://user-images.githubusercontent.com/73705144/116926220-8386f680-ac30-11eb-9054-32f8b1b22de0.png)

**Comment by vanpelt** [comment] 2021-05-03 20:27
Ok, change your call to wandb.init to be `wandb.init(..., settings=wandb.Settings(start_method="thread")` and that should fix it.

**Comment by thiagoribeiro1** [comment] 2021-05-04 14:35
I made the change as you suggested, @vanpelt! Thank you! And the following error appeared: 
![image](https://user-images.githubusercontent.com/73705144/117020375-c26a8a00-accc-11eb-99c7-00b75457a070.png)

**Comment by thiagoribeiro1** [comment] 2021-05-04 15:11
It seems to me like the code is failing to load the hyperparameters to start training the ANN. However, I followed the code example... :(

**Comment by vanpelt** [comment] 2021-05-04 19:32
The error is being caused by you accesing `config.n_layers`.  You must specify default attributes in your call to wandb.init before you can access attributes on the config object.  i.e.

```
config_defaults={
  "n_layers": 10
}
wandb.init(config=config_defaults)
```

**Comment by thiagoribeiro1** [comment] 2021-05-05 14:23
Hey @vanpelt. I did as you suggested and this is happening now :( 
![image](https://user-images.githubusercontent.com/73705144/117156516-260bba80-ad94-11eb-92f0-876efe57ce27.png)

I updated the code I am using at https://github.com/thiagoribeiro1/wandb/blob/main/train-cross-validation_VentilAQUA.py

Thank you for everything!

**Comment by thiagoribeiro1** [comment] 2021-05-05 14:27
And you can find the crashed runs and results at https://wandb.ai/thiagoribeiro1/uncategorized?workspace=user-thiagoribeiro1

**Comment by vanpelt** [comment] 2021-05-05 16:20
Can you try running an individual run outside of the agent to see if we can see what the actual error is?

**Comment by thiagoribeiro1** [comment] 2021-05-06 14:46
Yes, @vanpelt ... Now we can see the actual error:

**Comment by vanpelt** [comment] 2021-05-06 17:20
The error is saying you're trying to access an attribute on a `dict`.  i.e.

```
foo = {"bar": 1}
foo.bar #! will throw error
```

The `config` variable in your code is a dict.  It's not a `wandb.config` object.  Here's a really simple example of how `wandb.config` should work:

```
config_defaults = {"foo": 1}
wandb.init(config=config_defaults)
print("Foo: ", wandb.config.foo)
```

When this code is run within a sweep, "foo" would be overwritten with the current value for the trial instead of the default value of 1.

**Comment by thiagoribeiro1** [comment] 2021-05-06 17:35
@vanpelt, thank you very much. However, I am afraid that changing this part of the code will kill the cross-validation (k-fold). I am following the example given by WandB. Please, could you show me where exactly I have to make this change?

**Comment by thiagoribeiro1** [comment] 2021-05-06 17:44
@vanpelt, please, will I kill the cross-validation (k-fold) if a remove this line here https://github.com/thiagoribeiro1/wandb/blob/main/train-cross-validation_VentilAQUA.py#L115 ?

**Comment by vanpelt** [comment] 2021-05-06 18:00
You're converting the `wandb.config` object into a `dict` [here](https://github.com/thiagoribeiro1/wandb/blob/main/train-cross-validation_VentilAQUA.py#L196).  Either remove that conversion, or change your code to access the config object like a dict.  i.e. `config["n_layers"]` instead of `config.n_layers`.

**Comment by vanpelt** [comment] 2021-05-07 16:55
Try adding `settings=wandb.Settings(start_method="thread")` to your `wandb.init` call.

**Comment by thiagoribeiro1** [comment] 2021-05-07 18:22
@vanpelt, it is already there: https://github.com/thiagoribeiro1/wandb/blob/main/train-cross-validation_VentilAQUA.py#L107 :(

**Comment by anmolmann** [comment] 2021-12-03 01:45
@thiagoribeiro1 closing this thread. Questions can be redirected to the main [`client`](https://github.com/wandb/examples/issues) repo.

**Closed by anmolmann** 2021-12-03 01:45 UTC
